service:
  name: serverless-template

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  includeModules: false

package:
  individually: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    packager: 'yarn'
    includeModules: true

functions:
  myHandler:
    handler: src/handler.handle

